os: osx
osx_image: xcode13

language: swift

# Run XCUITests on every pull request
if: type = pull_request

before_install:
  - gem install fastlane --no-document

install: true

script:
  - fastlane scan --scheme TAU --device "iPhone 14 Pro Max"