os: osx
osx_image: xcode12.5

language: swift

branches:
  only:
    - organising-tests

before_install:
  - gem install fastlane --no-document

install: true

script:
  - fastlane scan --scheme TAU --device "iPhone 14 Pro Max"
