language: swift
osx_image: xcode10.1
branches:
  only:
    - organising-tests
before_install:
  - gem install fastlane --no-document
install: true
script:
  - fastlane scan --scheme TAU --device "iPhone 14 Pro Max"