language: swift
osx_image: xcode10.1
branches:
  only:
    - pull_request
before_install:
  - gem install fastlane --no-ri --no-rdoc --no-document
install: true
script:
  - fastlane scan --scheme TAU --device "iPhone 14 Pro Max"